contact_links:
  - name: Are you looking for documentation on moritzmaehr.ch?
    url: https://maehr.github.io/moritzmaehr.ch
    about: Please see the documentation for moritzmaehr.ch on its GitHub Pages page.
  - name: Do want to discuss moritzmaehr.ch with the community?
    url: https://github.com/maehr/moritzmaehr.ch/discussions
    about: Please see the discussions page for moritzmaehr.ch.
blank_issues_enabled: true
